//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConfigurationData.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class configure
    {
        public int configureId { get; set; }
        public string fromVariable { get; set; }
        public string fromValue { get; set; }
        public string toVariable { get; set; }
        public string toValue { get; set; }
        public Nullable<int> step { get; set; }
        public Nullable<bool> enabled { get; set; }
        public Nullable<System.DateTime> createdDateTime { get; set; }
        public string template { get; set; }
    }
}
