//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConfigurationData.Data
{
    using System;
    using System.Collections.Generic;
	using System.ComponentModel.DataAnnotations.Schema;

	[Table("ConfigurationUser")]
    public partial class ConfigurationUser: GenericCodes.Core.Entities.Entity
	{
		[Column("id")]
        public int id { get; set; }

		[Column("variable")]
		public string variable { get; set; }

		[Column("assignValue")]
		public string assignValue { get; set; }

		[Column("information")]
		public string information { get; set; }
        public Nullable<bool> inUse { get; set; }

		[Column("businessArea")]
		public string businessArea { get; set; }
    }
}
