//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConfigurationData.Data
{
    using System;
    using System.Collections.Generic;
	using System.ComponentModel.DataAnnotations;
	using System.ComponentModel.DataAnnotations.Schema;
	using GenericCodes.Core.Entities;

	[Table("fileReference",Schema ="meta")]
	public partial class FileReference: Entity 
    {
		[Column("fileReferenceId")]
        public int fileReferenceId { get; set; }

		[Column("fileName")]
		public string fileName { get; set; }

		[Column("directory")]
		public string directory { get; set; }

		[Column("fileType")]
		public string fileType { get; set; }

		[Column("information")]
		public string information { get; set; }

		[Column("required")]
		public Nullable<bool> required { get; set; }

		[Column("created")]
		public Nullable<System.DateTime> created { get; set; }
    }
}
