//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConfigurationData.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class linkedServerConfiguration
    {
        public int LinkedServerConfigurationId { get; set; }
        public string LinkedServerName { get; set; }
        public string SqlServerType { get; set; }
        public string ProviderName { get; set; }
        public string ProductName { get; set; }
        public string DataSource { get; set; }
        public string ProviderString { get; set; }
        public string CatalogName { get; set; }
        public string SecurityLocalLogin { get; set; }
        public string Impersonate { get; set; }
        public string RemoteUser { get; set; }
        public string RemotePassword { get; set; }
        public string ConnectionProperties { get; set; }
        public Nullable<bool> Required { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
    }
}
