//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConfigurationData.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Manipulation
    {
        public int manipulationId { get; set; }
        public string sourceTable { get; set; }
        public string sourceColumn { get; set; }
        public string ruleName { get; set; }
        public string fullSQL { get; set; }
        public Nullable<bool> enabled { get; set; }
        public string functionCall { get; set; }
        public string errorMessage { get; set; }
        public string sourceDb { get; set; }
        public Nullable<int> executableStep { get; set; }
    }
}
