//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConfigurationData.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pattern
    {
        public int patternId { get; set; }
        public string sourceString { get; set; }
        public string replaceString { get; set; }
        public string ruleName { get; set; }
        public Nullable<bool> active { get; set; }
        public Nullable<System.DateTime> createDateTime { get; set; }
        public Nullable<short> Step { get; set; }
        public string whereClause { get; set; }
        public Nullable<int> sequence { get; set; }
        public string actualString { get; set; }
        public string excludeString { get; set; }
    }
}
