//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConfigurationData.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class sourceTableColumn_Out
    {
        public int sourceTableColumnId { get; set; }
        public Nullable<int> sourceServerId { get; set; }
        public string sourceServer { get; set; }
        public string sourceSchema { get; set; }
        public Nullable<int> sourceTableId { get; set; }
        public string sourceTable { get; set; }
        public string sourceColumn { get; set; }
        public string sourceDataType { get; set; }
        public string sourceColumnLen { get; set; }
        public Nullable<bool> required { get; set; }
        public string baseTable { get; set; }
        public Nullable<System.DateTime> importDateTime { get; set; }
        public string importUser { get; set; }
        public string importFileName { get; set; }
        public Nullable<bool> transferred { get; set; }
        public Nullable<System.DateTime> transferDateTime { get; set; }
    }
}
