//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConfigurationData.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class sourceTable
    {
        public int sourceTableId { get; set; }
        public int sourceServerId { get; set; }
        public string sourceServer { get; set; }
        public string sourceSchema { get; set; }
        public string sourceTable1 { get; set; }
        public Nullable<bool> required { get; set; }
        public Nullable<System.DateTime> importDateTime { get; set; }
    }
}
