//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConfigurationData.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class sourceServer
    {
        public int sourceServerId { get; set; }
        public string sourceServerName { get; set; }
        public string sourceDatabase { get; set; }
        public string connection { get; set; }
        public Nullable<System.DateTime> createdDateTime { get; set; }
        public string linkedServer { get; set; }
        public string linkedServerString { get; set; }
        public string category { get; set; }
    }
}
