//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConfigurationData.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class source
    {
        public int sourceId { get; set; }
        public string sourceName { get; set; }
        public string sourceInformation { get; set; }
        public Nullable<int> relatedId { get; set; }
        public string relatedSource { get; set; }
        public Nullable<bool> required { get; set; }
        public Nullable<System.DateTime> created { get; set; }
    }
}
