//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConfigurationData.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class stageTable
    {
        public int stageTableId { get; set; }
        public int sourceServerId { get; set; }
        public int step { get; set; }
        public string sourceSchema { get; set; }
        public string sourceTable { get; set; }
        public Nullable<bool> required { get; set; }
        public Nullable<System.DateTime> createdDateTime { get; set; }
        public string source { get; set; }
        public Nullable<bool> load { get; set; }
        public Nullable<bool> persist { get; set; }
        public Nullable<bool> consolidate { get; set; }
        public string baseTable { get; set; }
    }
}
