//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConfigurationData.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class step
    {
        public int stepId { get; set; }
        public Nullable<int> siteId { get; set; }
        public string serverName { get; set; }
        public Nullable<short> step1 { get; set; }
        public string code { get; set; }
        public string executable { get; set; }
        public Nullable<bool> enabled { get; set; }
        public string information { get; set; }
    }
}
