//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConfigurationData.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tableColumn_import_Old20200123
    {
        public int tableColumn_importId { get; set; }
        public string sourceServer { get; set; }
        public string sourceSchema { get; set; }
        public string sourceTable { get; set; }
        public string sourceColumn { get; set; }
        public string sourceDataType { get; set; }
        public string sourceColumnLen { get; set; }
        public Nullable<bool> required { get; set; }
        public string validate { get; set; }
        public string lookup { get; set; }
        public Nullable<bool> trim_l { get; set; }
        public Nullable<bool> trim_r { get; set; }
        public string defaultValue { get; set; }
        public string outputTable { get; set; }
        public string outputColumn { get; set; }
        public string displayColName { get; set; }
        public string requiredDataType { get; set; }
        public string requiredColumnLen { get; set; }
        public string information { get; set; }
        public string baseTable { get; set; }
        public Nullable<System.DateTime> importDateTime { get; set; }
        public string importUser { get; set; }
        public string importFileName { get; set; }
        public Nullable<bool> transferred { get; set; }
        public Nullable<System.DateTime> transferDateTime { get; set; }
    }
}
