//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConfigurationData.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class touched
    {
        public int touchedId { get; set; }
        public string sourceSchema { get; set; }
        public string sourceTable { get; set; }
        public Nullable<System.DateTime> touchDate { get; set; }
        public Nullable<System.TimeSpan> touchtime { get; set; }
    }
}
