//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConfigurationData.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class word
    {
        public int PatternId { get; set; }
        public string What { get; set; }
        public string CanonicalVersion { get; set; }
        public bool Enabled { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
